site_name: YNAB CLI
site_url: https://jeffsawatzky.github.io/ynab-cli/
repo_url: https://github.com/jeffsawatzky/ynab-cli

theme:
  name: material
  features:
    - content.code.copy

plugins:
  - search

markdown_extensions:
    - admonition
    - attr_list
    - mkdocs-click
    - pymdownx.details
    - pymdownx.highlight:
        anchor_linenums: true
        line_spans: __span
        pygments_lang_class: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences

nav:
  - Home: index.md
  - Transaction Rules: transaction_rules.md
