"""
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.72.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
from enum import Enum
from typing import Self


class ScheduledTransactionFrequency(str, Enum):
    """
    The scheduled transaction frequency
    """

    """
    allowed enum values
    """
    NEVER = "never"
    DAILY = "daily"
    WEEKLY = "weekly"
    EVERYOTHERWEEK = "everyOtherWeek"
    TWICEAMONTH = "twiceAMonth"
    EVERY4WEEKS = "every4Weeks"
    MONTHLY = "monthly"
    EVERYOTHERMONTH = "everyOtherMonth"
    EVERY3MONTHS = "every3Months"
    EVERY4MONTHS = "every4Months"
    TWICEAYEAR = "twiceAYear"
    YEARLY = "yearly"
    EVERYOTHERYEAR = "everyOtherYear"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ScheduledTransactionFrequency from a JSON string"""
        return cls(json.loads(json_str))
