"""
YNAB API Endpoints

Our API uses a REST based design, leverages the JSON data format, and relies upon HTTPS for transport. We respond with meaningful HTTP response codes and if an error occurs, we include error details in the response body.  API Documentation is at https://api.ynab.com

The version of the OpenAPI document: 1.72.1
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""

from __future__ import annotations

import json
from enum import Enum
from typing import Self


class TransactionFlagColor(str, Enum):
    """
    The transaction flag
    """

    """
    allowed enum values
    """
    RED = "red"
    ORANGE = "orange"
    YELLOW = "yellow"
    GREEN = "green"
    BLUE = "blue"
    PURPLE = "purple"
    NULL = "null"

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TransactionFlagColor from a JSON string"""
        return cls(json.loads(json_str))
